id: AF9F8A68C
title: ยง18
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:16:25.836071
  last_modified_at: 2022-03-01 21:16:25.836094
