id: AF9F8A68C
title: ยง10
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 21:16:25.821690
  last_modified_at: 2022-03-01 21:16:25.821697
